### ISSUE TITLE
Bug in built in module `contextlib` causes excessive printing of exceptions in `futures.create_task`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/plumpy#168]
When exiting the context of the `run_task` in the `create_task` utiity, which happens when the corresponding loop is closed, we see the following
```
Exception ignored in: <generator object create_task.<locals>.run_task at 0x7f174d3ce6d0>
Traceback (most recent call last):
  File "/home/sph/code/aiida/env/dev/plumpy/plumpy/futures.py", line 102, in run_task
  File "/usr/lib/python3.7/contextlib.py", line 158, in __exit__
AttributeError: 'NoneType' object has no attribute 'exc_info'
```
These exceptions do not not show up in Python 3.8, but do for lower version. Have confirmed it for Py 3.5 and 3.7. The exception seems to come from the following line in the Python built in module `contextlib`:
https://github.com/python/cpython/blob/4e02981de0952f54bf87967f8e10d169d6946b40/Lib/contextlib.py#L158
Somehow, it seems that at that point `sys` is already `None`.

**Comment by sphuber** [comment]
Fixed in PR #169 and released in `0.15.1`
